### ISSUE TITLE
Results about graph signal reconstruction

### ISSUE THREAD

**Issue by wangfuli** [FilippoMB/Spectral-Clustering-with-Graph-Neural-Networks-for-Graph-Pooling#32]
Dear authors,

Thank you so much for making this work public!

I've been trying to reproduce the graph signal reconstruction results from your paper using the same ring and grid dataset you generated. For the graph u-net, using the built-in model in pyg (torch_geometric.nn.GraphUNet),  I was getting results that look better than what you reported in the paper. The code and the result I obtained can be found here (https://drive.google.com/drive/folders/1WXe18TUM0J9dPQOHP8PVkWFcrF41sisV?usp=sharing)

If you do not have time to check the code, would you mind sharing the code you used to reconstruct graph signals for topKPooling? I can cross-check if I messed up with something.

Thank you so much for your attention.

Best regards,
Fuli

**Comment by FilippoMB** [comment]
Dear Fuli,

I think the problem is that the Unet you are using has residual connections. In an autoencoding task, it makes no sense because the model can just learn to skip the bottleneck by using the residual connections and just copy the input into the output.

I didn't have time to look into it closely, but maybe you can replicate our setting by removing the residual connections in the Unet architecture. For example, in `graph_unet.py` replace line 122

````python
x = res + up if self.sum_res else torch.cat((res, up), dim=-1)
`````

with 

````python 
x = up
````

Let me know how it goes!

Filippo
